import Head from "next/head";
import AppInfo from "../components/must-hodl/AppInfo";
import Hero from "../components/must-hodl/Hero";
import { NextPage } from "next";

const About: NextPage = () => {
  return (
    <>
      <Head>
        <title>MustHodl</title>
        <meta name="Accounts" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="app bg-base-200">
        <Hero />
        <AppInfo />
      </div>
    </>
  );
};

export default About;
